### ISSUE TITLE
Velocity Vars Doc

### ISSUE THREAD

**Issue by mfreeman-xtivia** [telosys-tools-bricks/telosys-tools-commons#1]
Is there a documented list of the velocity variables that are available to template writers?

**Comment by l-gu** [comment]
If you are using Eclipse to see all the standard context objects just press "F1"
You can also use "$" + Ctrl-Space for object autocompletion( or $xxx. for field autocompletion)
Regarding simple variables, they are defined by the user (in the "Variables" tab in Eclipse project config)
If you are using Telosys-CLI you can define/see the variables in the "telosys-tools.cfg" 
A variable is "ProjectVariable.YouVarName = value"
A online documentation will be published soon

**Comment by mfreeman-templates** [comment]
Thank you very much. This is helpful--I also had  a RTFM moment and realized that documentation is there as Eclipse Help content.

Is the new DSL grammar/syntax documented anywhere?
